In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

![join](./img/joins.png)

## INNER JOIN

![inner join](./img/inner_join.png)

In [4]:
left_table = {'Date': ['01-01-2020', '02-01-2020', '03-01-2020', '04-01-2020' ],
              'CountryID': [1,1,3,2],
              'Units': [40, 25, 30, 35]}

In [5]:
# create a dataframe left_table_df
left_table_df = pd.DataFrame(left_table)
left_table_df

         Date  CountryID  Units
0  01-01-2020          1     40
1  02-01-2020          1     25
2  03-01-2020          3     30
3  04-01-2020          2     35

In [6]:
right_table = {'CountryID': [3,4],
              'Country': ['Panama', 'Spain']}

In [10]:
# create a dataframe right_table_df
right_table_df = pd.DataFrame(right_table)
right_table_df

   CountryID Country
0          3  Panama
1          4   Spain

In [ ]:
# Inner join inner_df 

inner_df = left_table_df.merge(right_table_df,on='CountryID')
inner_df

         Date  CountryID  Units Country
0  03-01-2020          3     30  Panama

In [ ]:
right_table = {'ID': [3,4],
              'Country': ['Panama', 'Spain']}

In [13]:
right_table_df = pd.DataFrame(right_table)
right_table_df

   ID Country
0   3  Panama
1   4   Spain

In [21]:
inner_df = left_table_df.merge(right_table_df,left_on='CountryID',right_on='ID')
inner_df

         Date  CountryID  Units Country_x  ID Country_y
0  03-01-2020          3     30       KSA   3    Panama

In [16]:
# with ,suffixes=['left','right'],

left_table = {'Date': ['01-01-2020', '02-01-2020', '03-01-2020', '04-01-2020' ],
              'CountryID': [1,1,3,2],
              'Units': [40, 25, 30, 35],
             'Country':['Pakistan', 'India', 'KSA', 'USA']}

In [17]:
left_table_df = pd.DataFrame(left_table)
left_table_df

         Date  CountryID  Units   Country
0  01-01-2020          1     40  Pakistan
1  02-01-2020          1     25     India
2  03-01-2020          3     30       KSA
3  04-01-2020          2     35       USA

In [ ]:
inner_df = left_table_df.merge(right_table_df,left_on='CountryID',right_on='ID',suffixes=['_left','_right'])
inner_df

         Date  CountryID  Units Country_left  ID Country_right
0  03-01-2020          3     30          KSA   3        Panama

## LEFT JOIN

![left join](./img/left_join.png)

In [25]:
left_table = {'Date': ['01-01-2020', '02-01-2020', '03-01-2020', '04-01-2020' ],
              'CountryID': [1,1,3,4],
              'Units': [40, 25, 30, 35]}

In [26]:
right_table = {'ID': [1,2, 3],
              'Country': ['USA', 'Canada', 'Panama']}

In [27]:
right_table_df = pd.DataFrame(right_table)
left_table_df = pd.DataFrame(left_table)

In [28]:
# use how
left_merged_df = left_table_df.merge(right_table_df,left_on='CountryID',right_on='ID',how='left')
left_merged_df

         Date  CountryID  Units   ID Country
0  01-01-2020          1     40  1.0     USA
1  02-01-2020          1     25  1.0     USA
2  03-01-2020          3     30  3.0  Panama
3  04-01-2020          4     35  NaN     NaN

## RIGHT JOIN

![right join](./img/right_join.png)

In [29]:
left_table = {'Date': ['01-01-2020', '02-01-2020', '03-01-2020', '04-01-2020' ],
              'CountryID': [1,1,3,4],
              'Units': [40, 25, 30, 35]}

In [36]:
right_table = {'CountryID': [3, 5],
              'Country': ['Panama', 'Russia']}

In [37]:
left_table_df = pd.DataFrame(left_table)
left_table_df

         Date  CountryID  Units
0  01-01-2020          1     40
1  02-01-2020          1     25
2  03-01-2020          3     30
3  04-01-2020          4     35

In [38]:
right_table_df = pd.DataFrame(right_table)
right_table_df

   CountryID Country
0          3  Panama
1          5  Russia

In [39]:
right_merged = left_table_df.merge(right_table_df, how='right',left_on='CountryID',right_on='CountryID')
right_merged

         Date  CountryID  Units Country
0  03-01-2020          3   30.0  Panama
1         NaN          5    NaN  Russia

In [41]:
# Same results using left join
right_merged = right_table_df.merge(left_table_df, how='left',left_on='CountryID',right_on='CountryID')
right_merged

   CountryID Country        Date  Units
0          3  Panama  03-01-2020   30.0
1          5  Russia         NaN    NaN

## FULL/OUTER JOIN 

![full join](./img/full_outer_join.png)

In [2]:
left_table = {'Date': ['01-01-2020', '02-01-2020', '03-01-2020', '04-01-2020' ],
              'CountryID': [1,1,3,2],
              'Units': [40, 25, 30, 35]}

In [3]:
right_table = {'ID': [1,2,3,4],
              'Country': ['USA', 'Canada', 'Panama', 'Spain']}

In [4]:
left_table_df = pd.DataFrame(left_table)
left_table_df

         Date  CountryID  Units
0  01-01-2020          1     40
1  02-01-2020          1     25
2  03-01-2020          3     30
3  04-01-2020          2     35

In [5]:
right_table_df = pd.DataFrame(right_table)
right_table_df

   ID Country
0   1     USA
1   2  Canada
2   3  Panama
3   4   Spain

In [10]:
full_merged = left_table_df.merge(right_table_df, how='outer',left_on='CountryID',right_on='ID').drop('ID',axis=1)
full_merged

         Date  CountryID  Units Country
0  01-01-2020        1.0   40.0     USA
1  02-01-2020        1.0   25.0     USA
2  04-01-2020        2.0   35.0  Canada
3  03-01-2020        3.0   30.0  Panama
4         NaN        NaN    NaN   Spain

## Left Anti Join

![left anti](./img/left_anti_join.png)

In [11]:
left_table = {'Date': ['01-01-2020', '02-01-2020', '03-01-2020', '04-01-2020' ],
              'CountryID': [1,1,3,2],
              'Units': [40, 25, 30, 35]}

In [12]:
right_table = {'ID': [3,4],
              'Country': ['Panama', 'Spain']}

In [13]:
left_table_df = pd.DataFrame(left_table)
left_table_df

         Date  CountryID  Units
0  01-01-2020          1     40
1  02-01-2020          1     25
2  03-01-2020          3     30
3  04-01-2020          2     35

In [14]:
right_table_df = pd.DataFrame(right_table)
right_table_df

   ID Country
0   3  Panama
1   4   Spain

In [16]:
left_anti_merged = left_table_df.merge(right_table_df, how='left',left_on='CountryID',right_on='ID',indicator=True).drop('ID',axis=1)
left_anti_merged

         Date  CountryID  Units Country     _merge
0  01-01-2020          1     40     NaN  left_only
1  02-01-2020          1     25     NaN  left_only
2  03-01-2020          3     30  Panama       both
3  04-01-2020          2     35     NaN  left_only

In [17]:
left_anti_merged.loc[left_anti_merged['_merge'] =='left_only']

         Date  CountryID  Units Country     _merge
0  01-01-2020          1     40     NaN  left_only
1  02-01-2020          1     25     NaN  left_only
3  04-01-2020          2     35     NaN  left_only

## Right Anti Join

![right anti join](./img/right_anti_join.png)

In [25]:
left_table = {'Date': ['01-01-2020', '02-01-2020', '03-01-2020', '04-01-2020' ],
              'CountryID': [1,1,3,2],
              'Units': [40, 25, 30, 35]}

In [26]:
right_table = {'ID': [3,4],
              'Country': ['Panama', 'Spain']}

## Concatenation
- pandas **.concat()** can concatenate both vertically and horizentally
- **axis=0** for vertical

## Using append method
**.append()**
- Simplified version of **.concat()**
- suppor : **sort_index** and **sort**
- Not support : **keys** and **join** i:e. always **join == outer**

`Dataframe.append has been depreceated in the pandas>1.4`